import type {
  AbilityFamily,
  ArchetypeFamilyAffinity,
  ArchetypePreferredFamilies,
} from '../../types/abilities';

/**
 * Launch taxonomy — 8 families cover every current archetype with room to
 * grow. Expansion is one AbilityFamily record per addition (openEnded=true).
 *
 * See card-engine-ability-system-spec.md §4 for the family rationale and §5
 * for the archetype→family mapping below.
 *
 * visualTheme + promptRules stay empty at A1. They're populated at A8 when
 * canonical Leonardo prompts are approved per family.
 */
export const ABILITY_FAMILIES: AbilityFamily[] = [
  {
    id: 'martial',
    name: 'Martial',
    description:
      'Weapon-forward physical technique — cleaves, strikes, counters, combo chains. The default combat vocabulary.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'weapon-scaling damage',
      'multi-hit',
      'counterattack',
      'stance / combo triggers',
    ],
    sortOrder: 10,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'fire',
    name: 'Fire',
    description:
      'Ember, flame, and heat. Damage-over-time via Burn, area effects, and escalating aggression.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'burn status',
      'area damage',
      'ignite triggers',
      'consumable resource cost',
    ],
    sortOrder: 20,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'nature',
    name: 'Nature',
    description:
      'Growth, roots, thorns, restoration. Terrain, transformation, and cycles.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'heal-over-time',
      'thorns / retaliation',
      'root / control',
      'terrain effects',
    ],
    sortOrder: 30,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'holy',
    name: 'Holy',
    description:
      'Radiance, ward, cleansing, revival. Support and protection with punishing effects on cursed targets.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'shield / ward',
      'cleanse',
      'revive',
      'radiant bonus damage',
    ],
    sortOrder: 40,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'necromancy',
    name: 'Necromancy',
    description:
      'Death, decay, blood-cost, soul collection. Includes vampiric blood mechanics until Blood grows large enough to split off.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'sacrifice cost',
      'lifesteal',
      'delayed decay',
      'summon undead',
      'soul currency',
    ],
    sortOrder: 50,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'tech',
    name: 'Tech',
    description:
      'Overclock, targeting, energy systems, precision. The only family that consumes Tech resource.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'overclock / heat',
      'analysis / mark',
      'weapon systems',
      'barrier generation',
    ],
    sortOrder: 60,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'defense',
    name: 'Defense',
    description:
      'Guard, taunt, barriers, damage reduction. Resource-agnostic — mana-users and tech-users both draw from it.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'shield / barrier',
      'taunt',
      'damage reduction',
      'reflect',
      'guard triggers',
    ],
    sortOrder: 70,
    openEnded: true,
    status: 'active',
  },
  {
    id: 'beast',
    name: 'Beast',
    description:
      'Feral instinct, pack bonuses, companions, marking prey. Physical + primal, with hunt / prey conditionals.',
    visualTheme: '',
    promptRules: [],
    mechanicPreferences: [
      'mark prey',
      'summon companion',
      'pack bonus',
      'bleed status',
      'combo on marked targets',
    ],
    sortOrder: 80,
    openEnded: true,
    status: 'active',
  },
];

export const ABILITY_FAMILY_IDS = ABILITY_FAMILIES.map((f) => f.id);

/**
 * Archetype → family affinity. Preferred families are the archetype's core
 * identity; secondary are supported but rarer; restricted are lore-forbidden
 * and never generated by the ability candidate pass.
 *
 * See card-engine-ability-system-spec.md §5 for the lore rationale.
 */
const affinity = (
  preferred: string[],
  secondary: string[] = [],
  restricted: string[] = [],
): ArchetypeFamilyAffinity => ({ preferred, secondary, restricted });

export const ARCHETYPE_PREFERRED_FAMILIES: ArchetypePreferredFamilies = {
  Barbarian: affinity(['martial', 'beast'], ['fire', 'defense'], ['holy', 'necromancy', 'tech']),
  Monk: affinity(['martial', 'defense'], ['holy', 'nature'], ['necromancy', 'tech']),
  Beastmaster: affinity(['beast', 'nature'], ['martial'], ['tech']),
  Druid: affinity(['nature'], ['holy', 'beast'], ['tech', 'necromancy']),
  Necromancer: affinity(['necromancy'], ['nature'], ['holy', 'tech']),
  // Vampire uses the blood/lifesteal subset of Necromancy until Blood splits off.
  Vampire: affinity(['necromancy', 'martial'], ['beast'], ['holy', 'tech']),
  Lycanthrope: affinity(['beast', 'martial'], ['nature'], ['tech']),
  'Mech Pilot': affinity(['tech', 'defense'], ['martial'], ['nature', 'necromancy', 'holy']),
  Android: affinity(['tech'], ['defense', 'martial'], ['nature', 'necromancy']),
  Seraph: affinity(['holy', 'defense'], ['martial', 'nature'], ['necromancy']),
  Human: affinity(['martial', 'defense'], ['holy', 'nature', 'fire', 'beast'], []),
};

/** Returns the family record for an id, or undefined if the id is not registered. */
export function getFamily(id: string): AbilityFamily | undefined {
  return ABILITY_FAMILIES.find((f) => f.id === id);
}

/** True if the family id is registered as active. */
export function isFamilyActive(id: string): boolean {
  const f = getFamily(id);
  return f?.status === 'active';
}
