#!/usr/bin/env python3
"""
Pack the combat effect frames into Phaser spritesheets.

WHY THIS EXISTS. The elemental blast art was generated in PixelLab for the
boss battle and lives as ONE PNG PER FRAME — `lash/fire/stream-f0.png` through
`-f8.png` — because the React battle layer swaps an <img> src on a timer and
never needed a sheet. Phaser wants a strip and a frame size. That difference is
the only thing standing between 545 finished PNGs and the overworld using them,
so this packs them rather than anyone regenerating art that already exists.

The twin written beside each strip is the same shape the castle pipeline already
uses (see card-slam-sheet.json), so build-asset-pack.mjs can register these the
same way it registers everything else. Nothing here is hand-listed: run it again
after new effect art lands and the new clips appear.

A clip that exists only as a still (blood's impact, the volley shards) is packed
as a one-frame strip on purpose. The runtime then has ONE contract — every effect
is a sheet with a frame count — instead of branching on whether art happens to be
animated, which is exactly the sort of special case that rots.

Usage:
    python scripts/effects/pack_effects.py [--check]

    --check   exit non-zero if any strip is missing or stale, and write nothing.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
PUBLIC = HERE.parent.parent / "public"
EFFECTS = PUBLIC / "assets/combat/effects"
OUT = EFFECTS / "packed"

# Review leftovers and the packed output itself are not sources.
SKIP_DIRS = {"_candidates", "packed"}

FRAME_RE = re.compile(r"^(?P<clip>[a-z]+)-f(?P<index>\d+)\.png$")


def discover():
    """Every clip in the tree, as (form, element, clip, [frame paths])."""
    clips: list[tuple[str, str, str, list[Path]]] = []

    for form_dir in sorted(p for p in EFFECTS.iterdir() if p.is_dir()):
        if form_dir.name in SKIP_DIRS:
            continue
        for element_dir in sorted(p for p in form_dir.iterdir() if p.is_dir()):
            frames_by_clip: dict[str, dict[int, Path]] = {}
            stills: dict[str, Path] = {}

            for png in sorted(element_dir.glob("*.png")):
                m = FRAME_RE.match(png.name)
                if m:
                    frames_by_clip.setdefault(m["clip"], {})[int(m["index"])] = png
                else:
                    stills[png.stem] = png

            for clip, indexed in frames_by_clip.items():
                ordered = [indexed[i] for i in sorted(indexed)]
                clips.append((form_dir.name, element_dir.name, clip, ordered))

            # Stills only count when there is no animated version of the same clip.
            for clip, path in stills.items():
                if clip not in frames_by_clip:
                    clips.append((form_dir.name, element_dir.name, clip, [path]))

    return clips


def pack(form: str, element: str, clip: str, frames: list[Path], check: bool) -> tuple[str, bool]:
    """Write one strip and its twin. Returns (key, changed)."""
    key = f"fx-{form}-{element}-{clip}"
    images = [Image.open(f).convert("RGBA") for f in frames]

    widths = {im.width for im in images}
    heights = {im.height for im in images}
    if len(widths) != 1 or len(heights) != 1:
        raise SystemExit(
            f"{key}: frames are not all the same size ({sorted(widths)} x {sorted(heights)}). "
            "A sheet cannot describe a ragged clip; fix the source art."
        )

    fw, fh = images[0].width, images[0].height
    strip = Image.new("RGBA", (fw * len(images), fh), (0, 0, 0, 0))
    for i, im in enumerate(images):
        strip.paste(im, (i * fw, 0))

    png_path = OUT / f"{key}.png"
    json_path = OUT / f"{key}.json"
    twin = {
        "image": f"{key}.png",
        "frameWidth": fw,
        "frameHeight": fh,
        "frameCount": len(images),
        "columns": len(images),
        "rows": 1,
        "source": f"assets/combat/effects/{form}/{element}/",
        "note": (
            "Generated by scripts/effects/pack_effects.py from the per-frame PNGs "
            "PixelLab produced for the boss battle. Do not hand-edit; re-run the packer."
        ),
    }

    if check:
        if not png_path.exists() or not json_path.exists():
            return key, True
        existing = json.loads(json_path.read_text(encoding="utf-8"))
        stale = existing != twin or Image.open(png_path).size != strip.size
        return key, stale

    OUT.mkdir(parents=True, exist_ok=True)
    strip.save(png_path)
    json_path.write_text(json.dumps(twin, indent=2) + "\n", encoding="utf-8")
    return key, True


def main() -> int:
    check = "--check" in sys.argv
    if not EFFECTS.is_dir():
        print(f"No effects directory at {EFFECTS}", file=sys.stderr)
        return 1

    clips = discover()
    stale: list[str] = []
    for form, element, clip, frames in clips:
        key, changed = pack(form, element, clip, frames, check)
        if changed:
            stale.append(key)

    if check:
        if stale:
            print("Stale, run `npm run effects:pack`:")
            for key in stale:
                print(f"  - {key}")
            return 1
        print(f"Effect sheets are up to date ({len(clips)} clips).")
        return 0

    animated = sum(1 for *_, frames in clips if len(frames) > 1)
    print(f"Packed {len(clips)} effect clips ({animated} animated, {len(clips) - animated} stills).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
