import type { ArenaManifest } from './types';

/**
 * Arena backgrounds — Leonardo-generated painted 16:9 scenes with a HUD-safe
 * upper-left region and low-contrast lower foreground. Prompts live in
 * Combat_Art_Acquisition_and_Integration_Plan.md and get pasted into the
 * C6 PR body for approval. C5 ships placeholder rows only.
 */
export const ARENA_MANIFEST: ArenaManifest = {
  barbarian_moot_ground: {
    id: 'barbarian_moot_ground',
    kind: 'arena',
    source: 'leonardo',
    path: 'arenas/barbarian-moot-ground/base.png',
    dimensions: { width: 1359, height: 768 },
    approvalStatus: 'approved',
    promptVersion: 'arena.v3',
    notes:
      "The Debt-Bearer's home ground — a high ancestor moot-ground above a barbarian settlement. " +
      'Phoenix 1.0 with our own approved arena uploaded as a LOW-strength style reference (asking for ' +
      'pixel art in words does not work; High strength imported the reference\'s lava room wholesale), ' +
      'then pixelised deterministically by scripts/bg-harness/lib/pixelize.py. ' +
      'Contains NO dais: the boss platform is drawn in code by BossPlatform.tsx.',
  },
  forbidden_mountain_passage: {
    id: 'forbidden_mountain_passage',
    kind: 'arena',
    source: 'leonardo',
    path: 'arenas/forbidden-mountain-passage/base.png',
    dimensions: { width: 1360, height: 768 },
    approvalStatus: 'approved',
    promptVersion: 'p1.v1',
    notes:
      'Leonardo Phoenix 1.0 pixel-art pass (p1-candidate-4, seed=45ba9e9d job). ' +
      'Approved by Raheem 2026-07-20. Flat circular dais, gothic pilasters, ' +
      'lava-web floor, dark HUD-safe sky. Supersedes the C6 painted asset, ' +
      'archived at arenas/forbidden-mountain-passage/legacy-c6-painted.png. ' +
      'Losing p1-candidate-{1,2,3,5}.png kept on disk for reference.',
  },
  still_season_grove: {
    id: 'still_season_grove',
    kind: 'arena',
    source: 'leonardo',
    path: 'arenas/still-season-grove/base.png',
    // 1359, not 1360: pixelize.py emits `1360 // scale * scale` at scale 3.
    // barbarian-moot-ground is 1359 for the same reason.
    dimensions: { width: 1359, height: 768 },
    approvalStatus: 'candidate',
    promptVersion: 'arena.v5.gemini',
    notes:
      "The Still Season's home ground — an overgrown forest colosseum, two massive trees framing the " +
      'bowl, flowered tiers, a painted dais with his rune sigil. ' +
      'GENERATED BY RAHEEM IN GEMINI, NOT LEONARDO, and that is the headline: ten Leonardo images ' +
      'across four prompt rounds could not stop putting a bright band across the upper middle, and ' +
      'one non-Leonardo image cleared the brief. Its framing trees give the dark HUD corners that ' +
      '"name the object, do not negate the absence" was trying to buy. Different generator, different ' +
      'failure modes: it cost a LIT GATE sitting exactly where the boss\'s rune halo goes, and 15% ' +
      'magenta on the exact floor band BossFlowerBed fires into. Both fixed in post. ' +
      'FINISHED DETERMINISTICALLY by scripts/bg-harness/lib/finish_arena.py: ' +
      '--cut 0 --no-canopy --scale 3 --colors 128 --top-vignette 0.85 --top-vignette-reach 0.45 ' +
      '--damp-ramp --knockdown 0.40,0.30,0.58,0.58,0.45. ' +
      'The vignette is NOT cosmetic — the corner pass contributes nothing at x=0.5, and iPhone ' +
      'portrait cover-crops to the centre, so the bright sky became the top of the phone screen ' +
      '(measured p95 212 -> 114). ' +
      'CONTAINS A PAINTED DAIS, deliberately. The old "no dais" rule was over-broad: it meant no ' +
      'RAISED platform the sprite must stand on top of. BossPlatform draws a contact shadow, not a ' +
      'slab, and the sprite box bottom lands at a stable 66-70% of viewport height — on this dais, ' +
      'between its far edge (y 0.611) and near edge (y 0.92). That number is the real contract.',
  },
};

/**
 * The arena for a boss, falling back to the default when that boss has no
 * arena of its own or its arena has no art yet. Never returns undefined —
 * a missing background would render the fight on a blank void.
 */
/**
 * The colour the arena's own light throws up onto the fighters.
 *
 * This used to be hardcoded warm ember in BOTH scene trees, with a comment
 * saying it existed "to match the pixel arena's lava veins" — true of the one
 * arena that existed, and actively wrong for any other. Drop a grove or a
 * bone-white sanctum under an orange floor-glow and you get a forest lit from
 * below by a lava pool that is not there.
 *
 * Per-arena, so a new background cannot be sabotaged by the previous one's
 * lighting.
 */
export const ARENA_GROUND_TINT: Record<string, { mid: string; low: string }> = {
  // Cold dusk stone with a warm bleed from the ring's fire seams.
  barbarian_moot_ground: { mid: 'rgba(40,44,66,0.28)', low: 'rgba(90,45,20,0.45)' },
  forbidden_mountain_passage: { mid: 'rgba(60,18,8,0.30)', low: 'rgba(80,20,10,0.60)' },
  // Damp green from the overgrowth. Explicitly NOT the inherited ember values —
  // this is the exact case the comment above was written for: without its own
  // row, a forest would be lit from below by a lava pool that is not there.
  //
  // `low` was `rgba(96,30,52,0.42)`, a bruised magenta, authored when the plate
  // had no pink of its own. Against THIS plate it painted magenta straight back
  // over the bottom band that finish_arena.py had just spent a damping pass
  // clearing — two passes pointed at one band, pulling opposite ways, netting
  // out to nothing. Green now, so the floor stays clear for the attack VFX.
  still_season_grove: { mid: 'rgba(52,56,34,0.26)', low: 'rgba(30,52,38,0.38)' },
};

/** Falls back to the default arena's tint, matching resolveArenaFor. */
export function resolveGroundTint(arenaId: string | undefined) {
  return (
    (arenaId ? ARENA_GROUND_TINT[arenaId] : undefined) ??
    ARENA_GROUND_TINT[DEFAULT_ARENA_ID]
  );
}

export function resolveArenaFor(arenaId: string | undefined) {
  return (arenaId ? ARENA_MANIFEST[arenaId] : undefined) ?? ARENA_MANIFEST[DEFAULT_ARENA_ID];
}

export function getArena(arenaId: string) {
  return ARENA_MANIFEST[arenaId];
}

/** Default arena when a boss encounter doesn't specify one. */
export const DEFAULT_ARENA_ID = 'forbidden_mountain_passage';
