/**
 * The Card-wright's summoning performance — the approved one-shot card slam.
 *
 * Generated by scripts/sprite-lab (PixelLab) from the persistent Card-wright
 * character and approved by Raheem on 2026-08-07. The machine-readable twin is
 * public/assets/castle/hero/card-slam/card-slam-sheet.json; these numbers must
 * match it, so re-read that file after any regeneration rather than assuming.
 *
 * WHY THIS IS NOT PART OF HERO_SHEET. The walking avatar is a 36×71 grid of
 * four directions; this is a single 84×84 south-facing performance with its own
 * anchor and its own per-frame timing. Folding it into the walk sheet's contract
 * would force one of the two to lie about its frame size.
 *
 * WHAT PHASER OWNS. The sheet is the body performance and the blocking card prop
 * only. The draw flash, ground-slap impact, runes, dust, camera response, and the
 * overlay of the player's ACTUAL selected card are assembled in Phaser around it —
 * deliberately, so the same 17 frames serve every card in the game.
 *
 * TWO THINGS THAT MUST NOT BE DONE TO IT:
 *  - Do not body-height-normalize the crouch or the downward travel. The dip is
 *    the performance; matching it to the standing sprite's height removes the slam.
 *  - Do not downscale it at runtime. It was area-averaged to display resolution
 *    once, offline. Render at ~1:1 or upscaled.
 */

export const CARD_SLAM_SHEET = {
  key: 'hero-card-slam',
  path: '/assets/castle/hero/card-slam/card-slam-sheet.png',
  frameWidth: 84,
  frameHeight: 84,
  /** One horizontal row — frame index is the column. */
  columns: 17,
  frameCount: 17,
} as const;

/** Phaser animation key for the one-shot slam. */
export const CARD_SLAM_ANIM = 'hero-card-slam';

/**
 * Per-frame durations in milliseconds, NOT a uniform frame rate.
 *
 * The 280ms opening hold lets the presentation read before the motion starts, and
 * the 700ms final hold is the palm-down pose the summon resolves from. A uniform
 * frameRate collapses both and the ritual stops reading as a ritual.
 */
export const CARD_SLAM_DURATIONS_MS: readonly number[] = [
  280, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 700,
];

/**
 * Origin for the sprite, in the sheet's own coordinates. Feet-ish rather than
 * exactly 1.0 because the crouch travels below the standing contact line.
 */
export const CARD_SLAM_ANCHOR = { x: 0.5, y: 0.95 } as const;

/**
 * Only the south (screen-facing) direction exists. The other three were not
 * generated, on purpose — placement and timing get approved in play first, so
 * that generations are spent on poses the game is known to need.
 */
export const CARD_SLAM_FACING = 'down' as const;

/** Total run time, for sequencing the summon without waiting on an animation event. */
export const CARD_SLAM_TOTAL_MS = CARD_SLAM_DURATIONS_MS.reduce((a, b) => a + b, 0);
