/**
 * The castle hero's sprite sheet contract.
 *
 * Generated by scripts/sprite-lab (PixelLab) and packed by lib/pack.py, which
 * writes the machine-readable twin of this file to
 * public/assets/castle/hero/chibi.json. These numbers must match that file —
 * re-read it after any regeneration rather than assuming, because the model
 * overrides the requested frame size (we asked 128², it returned 180², and the
 * shared crop lands at 78×152).
 *
 * PRE-RESAMPLED TO DISPLAY RESOLUTION. The packed sheet was 78x152 per frame but
 * rendered at ~46% of that, so the GPU's nearest-neighbour downscale threw away
 * over half of every row and column each frame — the sprite read as mud. The
 * reduction now happens ONCE, offline, with area averaging and re-quantisation
 * (scripts/sprite-lab/lib/resample.py), and the renderer only ever upscales,
 * which is the direction pixel art tolerates. Never downscale pixel art at
 * runtime.
 *
 * TWO ART REGISTERS: this chibi sheet is the walking overworld avatar. The
 * detailed `hero-cardwright` art is reserved for dialogue portraits (see
 * scripts/sprite-lab/out/hero-cardwright/portrait.png) — chibi in the world,
 * detailed faces in conversation, as the genre does it.
 *
 * Layout is 4 rows × 7 columns: column 0 is the idle/standing frame, columns
 * 1–6 are the walk cycle. Frame index = row * columns + column.
 *
 * Row order is by SCREEN direction, not by the generator's compass labels.
 * PixelLab's `east` renders facing screen-left and `west` facing screen-right,
 * which is the opposite of the obvious reading — see the create-character-sprite
 * skill for the mirror-IoU test that establishes this.
 */

export const HERO_SHEET = {
  key: 'hero-chibi',
  path: '/assets/castle/hero/chibi.png',
  frameWidth: 36,
  frameHeight: 71,
  columns: 7,
} as const;

export type HeroFacing = 'down' | 'up' | 'left' | 'right';

/** Row index per screen direction, in the order pack.py writes them. */
const ROW: Record<HeroFacing, number> = {
  down: 0,
  up: 1,
  left: 2,
  right: 3,
};

export const HERO_FACINGS: HeroFacing[] = ['down', 'up', 'left', 'right'];

/** Animation key for a direction's walk cycle. */
export const walkKey = (facing: HeroFacing) => `hero-walk-${facing}`;

/** Standing frame — also the frame held when motion is reduced. */
export const idleFrame = (facing: HeroFacing) => ROW[facing] * HERO_SHEET.columns;

/** The six walk frames, skipping column 0 (which is the idle pose). */
export const walkFrames = (facing: HeroFacing) =>
  Array.from({ length: HERO_SHEET.columns - 1 }, (_, i) => ROW[facing] * HERO_SHEET.columns + 1 + i);

/**
 * On-screen hero height in world units, against a 1536×1152 courtyard plate.
 * The paving scale is the thing to tune against — a person should read as a
 * person next to the fountain, not as a doll or a giant.
 */
export const HERO_WORLD_HEIGHT = 100;

/** Walk cycle rate. Tied to movement speed at runtime so he doesn't skate. */
export const HERO_WALK_FPS = 10;

/** Feet-only collider, in world units — deliberately far smaller than the art. */
export const HERO_FEET = { width: 34, height: 20 } as const;
