/**
 * The Ember Jelly — the courtyard's first real enemy sprite.
 *
 * Generated by scripts/sprite-lab (PixelLab) 2026-08-15 from config
 * `prop-ember-jelly.json`, as an OBJECT rather than a character: a blob needs
 * no walk cycle, and object animation is the reliable route here (quadruped
 * character animation is 0-for-3 in this repo). The machine-readable twin is
 * public/assets/castle/construct/ember-jelly.json; these numbers must match it,
 * so re-read that file after any regeneration rather than assuming.
 *
 * IT REPLACES A RECTANGLE. Until now the training construct was drawn with
 * Phaser primitives — a deliberate 2026-08-13 ruling ("shapes, not sprites") so
 * that behaviour could be tuned before art was paid for. That worked: the state
 * machine, the pose math and the hit feel were all finished and playtested
 * before a single frame was bought.
 *
 * ONE STRIP, FOUR CLIPS, ADDRESSED BY FRAME RANGE. The clips are 7/9/7/9 frames
 * long, so a row grid would need padding; ranges into one strip waste nothing.
 * The order is the creature's life — idle, hop, gather, splat — not alphabetical.
 *
 * ZERO DIRECTIONS, AND THAT IS THE DESIGN. A symmetric blob reads the same from
 * every angle, so there are no facing rows to generate, mismatch, or maintain.
 * That is why this creature was chosen over anything with a front face.
 *
 * COLOUR IS FREE. Body and ember sit on separate palette ramps (verified by
 * recolouring shape B to moss, frost and void — the ember stayed red every
 * time), so a whole element family comes from scripts/sprite-lab/lib/recolor.py
 * for zero generations. Never regenerate this creature for hue.
 */

export const JELLY_SHEET = {
  key: 'construct-ember-jelly',
  path: '/assets/castle/construct/ember-jelly.png',
  frameWidth: 63,
  frameHeight: 54,
  /** One horizontal row — frame index is the column. */
  columns: 32,
  frameCount: 32,
} as const;


/**
 * Where the jelly's UNDERSIDE sits inside its frame, as a fraction of height.
 *
 * NOT 1.0, and that difference is why it floated. The packer leaves breathing
 * room below the ground line so a lunge or a shake cannot clip an edge pixel,
 * so the body's lowest opaque row is 50 of 54 -- four transparent pixels of
 * padding. Anchoring at the frame's bottom edge plants that PADDING on the
 * floor and leaves the creature hovering above it, which on a slime reads as
 * flying rather than as a sprite offset.
 *
 * Measured off the shipped strip, not guessed: resting frames bottom out at row
 * 50, mid-hop frames at 48 (it is off the ground -- that is the hop), and the
 * final splat frames at 54 as the puddle spreads past the standing footprint.
 * The anchor takes the RESTING row, so the creature stands correctly and the
 * hop genuinely leaves the floor.
 *
 * Same reason and same shape as KNOCKDOWN_ANCHOR in knockdownSprite.ts.
 */
export const JELLY_ANCHOR = 50 / 54;

export type JellyClipName = 'idle' | 'hop' | 'gather' | 'splat';

/**
 * Frame ranges into the single strip. `start` is the first frame index,
 * `frames` the count — mirrors the `clips` block in the twin JSON.
 */
export const JELLY_CLIPS: Record<
  JellyClipName,
  { start: number; frames: number; fps: number; loop: boolean }
> = {
  /** The resting wobble. Covers disabled, idle and alert. */
  idle: { start: 0, frames: 7, fps: 8, loop: true },
  /**
   * The hop. Plays while the construct approaches.
   *
   * Generated IN PLACE, with no horizontal travel in the frames: from a low
   * top-down view you cannot draw vertical displacement, so the clip carries
   * only the body's deformation and the runtime moves it across the ground.
   */
  hop: { start: 7, frames: 9, fps: 10, loop: true },
  /**
   * The telegraph — the body gathers into a tense ball over the ember.
   *
   * Loops, because the telegraph phase HOLDS for 650ms and that duration is a
   * fairness invariant, not a knob: the hero has no dodge, so the tell must be
   * long enough to walk out of. See combat/construct.ts telegraphIsAvoidable.
   */
  gather: { start: 16, frames: 7, fps: 9, loop: true },
  /**
   * Death. One-shot, holds on the last frame.
   *
   * The last frame is deliberately a legible corpse — a flat puddle with the
   * ember half-sunk in it — which makes it also the FIRST frame of the revive
   * when played in reverse. The revive therefore costs no extra art.
   */
  splat: { start: 23, frames: 9, fps: 12, loop: false },
};

/** Phaser animation keys, namespaced by sheet so they cannot collide. */
export const JELLY_ANIM = {
  idle: 'construct-ember-jelly-idle',
  hop: 'construct-ember-jelly-hop',
  gather: 'construct-ember-jelly-gather',
  splat: 'construct-ember-jelly-splat',
} as const satisfies Record<JellyClipName, string>;

/**
 * Frame indices for one clip, for Phaser's `generateFrameNumbers`.
 */
export function jellyFrames(clip: JellyClipName): number[] {
  const { start, frames } = JELLY_CLIPS[clip];
  return Array.from({ length: frames }, (_, i) => start + i);
}

/**
 * The body's palette ramp, for particles and tints that must match the sprite.
 *
 * Sampled from the shipped frames rather than eyeballed: these are the four
 * most common opaque colours in the idle frame, mid-ramp first. The death
 * burst feeds these to playDirectionalBurst so the goo that sprays off is the
 * same goo the body is made of.
 */
export const JELLY_PALETTE = ['#c97023', '#bb601f', '#e89331', '#d87d25'] as const;

/** The ember's own colour. Stays constant through every body recolour. */
export const JELLY_EMBER = '#8a2b18' as const;
