import { HERO_WORLD_HEIGHT } from './heroSprite';

/**
 * Courtyard shopkeepers.
 *
 * Deliberately shaped to be compatible with the `Stall` interface in
 * pages/castle/courtyard/stalls.ts (`id`, `label`, `x`, `y`, `width`, `height`,
 * `placeholder`) so the existing proximity ribbon and placeholder panel render
 * keepers with no new components. Keepers are, however, kept OUT of the
 * Directory — that lists places you can go, not people you can talk to.
 *
 * SOURCE ART WARNING: these characters were generated by hand in the PixelLab
 * web app and **no seed was recorded**, so they cannot be regenerated. The PNGs
 * under public/assets/castle/keepers/ are the only copy in existence — treat
 * them as source art, not as build output, and never delete them as "generated
 * files".
 */

export interface Keeper {
  id: string;
  /** Shown on the proximity ribbon and in the placeholder panel. */
  label: string;
  /** Ground-contact position in plate coordinates. */
  x: number;
  y: number;
  /** Proximity footprint, matching the Stall shape the overlay expects. */
  width: number;
  height: number;
  placeholder: string;

  sheet: { key: string; path: string; frameWidth: number; frameHeight: number; frameCount: number };
  /** Intended on-screen height in world units — apparent size is chosen here,
   *  never inherited from the generator's native canvas. */
  worldHeight: number;
  /** Feet-only collider so the hero can't walk through him. */
  feet: { width: number; height: number };
  /**
   * Breathing loop rate, for keepers with a real multi-frame animation.
   * Slow — they are standing still, not panting.
   */
  fps?: number;
  /**
   * Synthesized breath for a SINGLE-frame keeper, tweened in Phaser instead of
   * generated. See BREATH below for why this exists and when to prefer it.
   * Opt-in: a keeper without this simply stands still, which is correct for
   * scenery like the horse.
   */
  breath?: { amplitude: number; periodMs: number };
  /**
   * Whether the player can talk to them. Defaults to true.
   *
   * Scenery residents (a grazing horse) set this false: they still get a
   * collider so you walk around them, but no proximity ribbon and no Tab entry.
   * A prompt on a horse would advertise an interaction the game has no plan for,
   * and it would clutter the keyboard traversal order.
   */
  interactive?: boolean;
}

/**
 * Synthesized breath, shared by every single-frame keeper.
 *
 * WHY NOT A GENERATED ANIMATION: the archivist's `breathing-idle` came back with
 * her belt ledger teleporting between hips across the four frames and her hair
 * silhouette redrawn each time — the same per-frame redraw drift that changed
 * the hero's costume mid-walk. It is inherent to the animation service and no
 * generation parameter addresses it. Tweening one frame makes the defect
 * structurally impossible: there is only one image, so nothing can move that
 * isn't meant to.
 *
 * scaleY ONLY, never y. `y` is the ground line, and three systems compare it —
 * depth sorting, the contact shadow, and collider placement. Tweening it
 * desyncs all three for a cosmetic effect. With the feet origin, scaleY already
 * produces the head rise that a bob would be duplicating.
 *
 * PERIOD is set against the dwarf's real loop so the two read as the same
 * species. His 4 frames at fps 2 is a 2.0s cycle; 3.0s here is ~20 breaths/min,
 * a calm standing adult. They were 0.8s and 3.0s at first draft — a nearly 4x
 * mismatch, which is more legible on screen than either motion alone.
 *
 * AMPLITUDE is the tuning knob Raheem judges. At her ~68 display px, 1.015 is
 * about 1px of travel and 1.03 about 2px. Under NEAREST filtering 1px does not
 * animate so much as pop a single row in and out, so 1.03 is the default. Do
 * not exceed 1.04: a uniform scaleY lengthens legs that should not move.
 */
export const BREATH = { amplitude: 1.03, periodMs: 3000 } as const;

export const KEEPERS: Keeper[] = [
  {
    id: 'keeper-dwarf',
    label: 'The Card-wright',
    // Tucked against the striped awning stall he runs — he forges cards, so he
    // belongs at the Crafting Stall rather than adrift in open paving. Clear of
    // the barrel below (starts y≈550), with only a few px of head overlap on the
    // wares table. Re-check if the plate is ever regenerated.
    x: 1150,
    y: 540,
    width: 90,
    height: 110,
    placeholder:
      'The dwarf who forges cards at this stall. Dialogue is not built yet — he has nothing to say so far.',

    // Sheet is pre-resampled OFFLINE to display resolution (was 79x125). Pixel
    // art must never be downscaled at runtime: at 46% the GPU's nearest sampling
    // dropped over half his rows and columns, shredding the dreads and outline
    // into noise — that was the "not from the same game" muddiness. Rendered now
    // at ~1:1 or gently upscaled, which pixel art tolerates.
    sheet: {
      key: 'keeper-dwarf',
      path: '/assets/castle/keepers/dwarf-breathe.png',
      frameWidth: 37,
      frameHeight: 58,
      frameCount: 4,
    },
    // 0.82x the hero, which is how he was generated (119px body vs the hero's
    // 146px). A dwarf SHOULD be shorter; the point is that it's a decision.
    worldHeight: Math.round(HERO_WORLD_HEIGHT * 0.82),
    feet: { width: 30, height: 16 },
    // His generated loop is genuinely clean (body height constant, centroid
    // range 0.46px, no prop drift) so he keeps it. fps 2 = a 2.0s cycle; at the
    // original 5 he took 75 breaths a minute, which is hyperventilation, and it
    // clashed badly with the archivist's 3.0s tween.
    fps: 2,
  },

  {
    id: 'keeper-archivist',
    label: 'The Archivist',
    // At the window booth's counter line, above the Collection collider
    // (which starts y≈685). She keeps The Collection, so the stall and the
    // person tell the same story.
    x: 1235,
    y: 665,
    width: 84,
    height: 108,
    placeholder:
      'She keeps The Collection — every character you have gathered. Dialogue is not built yet.',

    // ONE frame, breathed by tween — see BREATH above. This is frame 2 of her
    // original four, chosen because it is the only one where she holds the bound
    // ledger in her hand rather than wearing it as a hip pouch; a held book also
    // survives the drop to ~68px far better, which was a separate complaint.
    //
    // Her other three frames stay in scripts/sprite-lab/out/keeper-archivist/.
    // Her SEED was never recorded, so she can never be rebuilt — those PNGs are
    // the only copy of this character that will ever exist.
    sheet: {
      key: 'keeper-archivist',
      path: '/assets/castle/keepers/archivist-breathe.png',
      frameWidth: 30,
      frameHeight: 69,
      frameCount: 1,
    },
    // Slightly under the hero: a slight-build young adult. Note her NATIVE
    // sprite was 214px tall against the dwarf's 119 from identical settings —
    // native size follows the pipeline and is not controllable, so apparent
    // height is always chosen here instead.
    worldHeight: Math.round(HERO_WORLD_HEIGHT * 0.98),
    feet: { width: 26, height: 14 },
    breath: BREATH,
  },

  {
    id: 'prop-horse',
    label: 'Horse',
    // The open space below the stall, up and to the right of the water barrel.
    // Traced against the plate: produce table y 695–772, barrel x 1220–1267 /
    // y 775–840, building edge from x≈1335. His feet box lands x 1267–1343 /
    // y 757–775, clear of the barrel.
    x: 1305,
    y: 782,
    width: 120,
    height: 80,
    placeholder: '',
    // SCENERY: solid so the player walks around him, but no ribbon and no Tab
    // entry. A prompt on a horse would advertise an interaction that does not
    // exist and would clutter keyboard traversal.
    interactive: false,

    sheet: {
      key: 'prop-horse',
      path: '/assets/castle/keepers/horse-eating.png',
      frameWidth: 58,
      frameHeight: 59,
      // STATIC, one frame, and deliberately NOT breathed by tween. A uniform
      // scaleY on a head-down quadruped raises rump and muzzle by the same
      // amount, which reads as the whole animal inflating rather than a jaw
      // moving. Ambiguous enough to pass for breathing on a biped; unmistakably
      // wrong on a horse. Real chewing needs a real animation — see the
      // playbook for the attempts against the quadruped `eating` templates.
      //
      // Note his hay is baked into this sprite, which rules out any template
      // that raises his head: it would detach him from his own hay pile.
      frameCount: 1,
    },
    worldHeight: 84,
    // Wide, shallow footprint — he is a quadruped standing side-on.
    feet: { width: 76, height: 18 },
  },
];

/** Animation key for a keeper's idle loop. */
export const keeperIdleKey = (id: string) => `${id}-breathe`;
