/**
 * The Card-wright's fall — the clip that plays when his cards go everywhere.
 *
 * Generated by scripts/sprite-lab (PixelLab) from the same persistent character
 * as the walk and the card slam, 2026-08-12, 8 generations for one south-facing
 * v3 clip. The machine-readable twin is
 * public/assets/castle/hero/knockdown/knockdown-sheet.json; these numbers must
 * match it, so re-read that file after any regeneration rather than assuming.
 *
 * RESAMPLED SO HIS STANDING HEIGHT IS EXACTLY 71px — the walking sheet's height.
 * The source frames are 208x236 and were area-averaged down once, offline, to
 * 99x112. Getting this wrong is not subtle: he would visibly change size on the
 * frame the fall begins, which reads as the wrong character being swapped in.
 *
 * WHY THE FRAME IS WIDER THAN THE WALK'S. A sprawled figure is wider than it is
 * tall — content runs 60x149 standing and 140x77 on the ground. Trimming that to
 * the walk sheet's 36x71 box would clip his own arms off, so the box is generous
 * and the anchor does the aligning.
 *
 * TIMED TO THE STATE MACHINE, not the other way round: the durations sum to
 * exactly ACTION_TIMING.knockdownMs. The trip runs fast and the sprawl holds,
 * because the hold is what gives the player time to see where their cards landed.
 */

export const KNOCKDOWN_SHEET = {
  key: 'hero-knockdown',
  path: '/assets/castle/hero/knockdown/knockdown-sheet.png',
  frameWidth: 99,
  frameHeight: 112,
  /** One horizontal row — frame index is the column. */
  columns: 13,
  frameCount: 13,
} as const;

/** Phaser animation key for the one-shot fall. */
export const KNOCKDOWN_ANIM = 'hero-knockdown';

/**
 * Per-frame durations in milliseconds, summing to 1200 — the knockdown phase.
 *
 * WAS 45ms a frame, which put the entire fall on screen in 540ms. Raheem,
 * watching it: "the fall animation is way too fast for a human to see. It just
 * doesn't look good." He was right — twelve frames at 45ms is a flicker, not a
 * fall, and it is why the knockdown read as a dark smear rather than a man
 * going down.
 *
 * 85ms a frame is roughly 12fps: slow enough to read the stagger and the tip,
 * still quick enough to feel like an impact rather than a swoon. The last frame
 * is short because it is no longer where he waits — he now HOLDS on the ground
 * until the player asks to get up, so the lying-down time is unbounded and
 * belongs to the state machine rather than to this table.
 */
export const KNOCKDOWN_DURATIONS_MS: readonly number[] = [
  85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 180,
];

/** Total run time. Matches ACTION_TIMING.knockdownMs by construction. */
export const KNOCKDOWN_TOTAL_MS = KNOCKDOWN_DURATIONS_MS.reduce((a, b) => a + b, 0);

/**
 * Feet origin — MEASURED from the art, not copied from another clip.
 *
 * 0.95 was inherited from the card slam and is wrong here: every knockdown frame
 * carries an empty skirt below the feet (24px while he is still upright), where
 * the walking sheet's feet sit 1px off the frame bottom. Rendered at the walk's
 * origin of 1.0 the whole body lifts about 24 world pixels the instant the
 * texture swaps, which reads as him leaving the ground rather than falling to it.
 *
 * 88/112 = 0.786 is the row his feet actually occupy in frame 0, so the swap
 * keeps his feet where his feet were.
 */
export const KNOCKDOWN_ANCHOR = { x: 0.5, y: 0.786 } as const;

/**
 * Only the south (screen-facing) direction exists, deliberately.
 *
 * Animation is per-direction, so a clip only exists on the faces we pay for.
 * The other three extend from the same animation_group_id later, charging only
 * for the new directions — and only once the pose has been approved in play.
 */
export const KNOCKDOWN_FACING = 'down' as const;
