/**
 * The Card-wright's fall — the clip that plays when his cards go everywhere.
 *
 * Generated by scripts/sprite-lab (PixelLab) from the same persistent character
 * as the walk and the card slam, 2026-08-12, 8 generations for one south-facing
 * v3 clip. The machine-readable twin is
 * public/assets/castle/hero/knockdown/knockdown-sheet.json; these numbers must
 * match it, so re-read that file after any regeneration rather than assuming.
 *
 * RESAMPLED SO HIS STANDING HEIGHT IS EXACTLY 71px — the walking sheet's height.
 * The source frames are 208x236 and were area-averaged down once, offline, to
 * 99x112. Getting this wrong is not subtle: he would visibly change size on the
 * frame the fall begins, which reads as the wrong character being swapped in.
 *
 * WHY THE FRAME IS WIDER THAN THE WALK'S. A sprawled figure is wider than it is
 * tall — content runs 60x149 standing and 140x77 on the ground. Trimming that to
 * the walk sheet's 36x71 box would clip his own arms off, so the box is generous
 * and the anchor does the aligning.
 *
 * TIMED TO THE STATE MACHINE, not the other way round: the durations sum to
 * exactly ACTION_TIMING.knockdownMs. The trip runs fast and the sprawl holds,
 * because the hold is what gives the player time to see where their cards landed.
 */

export const KNOCKDOWN_SHEET = {
  key: 'hero-knockdown',
  path: '/assets/castle/hero/knockdown/knockdown-sheet.png',
  frameWidth: 99,
  frameHeight: 112,
  /** One horizontal row — frame index is the column. */
  columns: 13,
  frameCount: 13,
} as const;

/** Phaser animation key for the one-shot fall. */
export const KNOCKDOWN_ANIM = 'hero-knockdown';

/**
 * Per-frame durations in milliseconds, summing to 900 — the knockdown phase.
 *
 * Not a uniform frame rate: twelve fast frames carry the stagger and the tip,
 * and the last one holds for 360ms on the ground.
 */
export const KNOCKDOWN_DURATIONS_MS: readonly number[] = [
  45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 360,
];

/** Total run time. Matches ACTION_TIMING.knockdownMs by construction. */
export const KNOCKDOWN_TOTAL_MS = KNOCKDOWN_DURATIONS_MS.reduce((a, b) => a + b, 0);

/**
 * Feet origin, matching the walking sheet so he does not jump on the frame the
 * fall starts.
 */
export const KNOCKDOWN_ANCHOR = { x: 0.5, y: 0.95 } as const;

/**
 * Only the south (screen-facing) direction exists, deliberately.
 *
 * Animation is per-direction, so a clip only exists on the faces we pay for.
 * The other three extend from the same animation_group_id later, charging only
 * for the new directions — and only once the pose has been approved in play.
 */
export const KNOCKDOWN_FACING = 'down' as const;
